### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by asadmehdi785** [MissRach89/ColmarAcademy#6]
Overall, outstanding work on this project! You did an excellent job in all aspects of the project, from keeping your code and project contents organized to implementing the specification. Very well done! I thought the website looked very clean and you definitely put a lot of time making sure the styling for everything was just right, while also keeping it very responsiveness. I also liked the inclusion of the JavaScript for the carousel effect.

Great work overall! I hope you enjoyed the course!

Grade: **Exceeds expectations**

**Comment by MissRach89** [comment]
@asadmehdi785  Thank you so much for the nice feedback! I was really happy with how I did and have enjoyed the course a lot! If anything it's taught me a new degree of empathy for the developers I work with. It's harder than it looks to execute a nice UI.
